music/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
app_name='music'

urlpatterns = [
    # /music/
    path('', views.IndexView.as_view(), name='index'),
    
    #/music/71/
    # url(r'^?P<album_id>[0-9]+)/$', views.detail, name='detail'')
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),

    #/music/album/add/
    path('album/add/', views.AlbumCreate.as_view(), name='album-add'),

    #/music/album/2/
    path('album/<int:pk>/', views.AlbumUpdate.as_view(), name='album-update'),

    #/music/album/2/delete
    path('album/<int:pk>/delete/', views.AlbumDelete.as_view(), name='album-delete'),
]

website/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include('music.urls')),
]

music/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Album(models.Model):
    artist = models.CharField(max_length=200)
    album_title = models.CharField(max_length=300)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)
    
    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk' : self.pk})


    def __str__(self):
        return self.album_title + ':' + self.artist
    
class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=200)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Album

class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums'

    def get_queryset(self):
        return Album.objects.all()

class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'

class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']
    
class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add a new album{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12">
            <div class="panel panel-default">

                <div class="panel-body">
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>

            </div>
        </div>
        
    </div>

</div>
{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title> {% block title %} Rocking {% endblock %}</title>
        <!-- Loads path to static files -->
        {% load static %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
        <link href="https://fonts.googleapis.com/css?family=Chelsea+Market" rel="stylesheet" type="text/css" />
        <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    </head>

    <body>
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">

                <!--Header-->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'music:index' %}">Rocking</a>
                </div>

                <!--Items-->
                <div class="collapse navbar-collapse" id="topNavBar">

                    <ul class="nav navbar-nav">
                        <li class="active">
                            <a href="{% url 'music:index' %}">
                                <span class="glyphicon glyphicon-cd" area-hidden="true"></span>&nbsp; Albums
                            </a>
                        </li>
                        <li class="">
                            <a href="#">
                                <span class="glyphicon glyphicon-music" area-hidden="true"></span>&nbsp; Songs
                            </a>
                        </li>
                    </ul> 

                    <form class="navbar-form navbar-left" role="search" method="get" action="#">
                        <div class="form-group">
                            <input type="text" class="form-control" name="q" value="" placeholder="Search here">
                        </div> 
                        <button type="submit" class="btn btn-default">Search</button>
                    </form>

                    <ul class="nav navbar-nav navbar-right">
                        <li class="">
                            <a href="{% url 'music:album-add' %}">
                                <span class="glyphicon glyphicon-plus" area-hidden="true"></span>&nbsp; Add Album
                            </a>
                        </li>
                        <li class="">
                            <a href="#">
                                <span class="glyphicon glyphicon-off" area-hidden="true"></span>&nbsp; Logout
                            </a>
                        </li>
                    </ul>
        
                </div>

            </div>
        </nav>
        {% block body %}
        {% endblock %}
    </body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}

{% block title %} Album Details {% endblock %}

{% block body %}

    <img src="{{ album.album_logo }}"> 

    <h1>{{ album.album_title }}</h1>
    <h3>{{ album.artist }}</h3>

    <!-- <ul>
        {% for song in album.song_set.all%}
            <li>{{ song.song_title }} - {{ song.file_type }}</li>
        {% endfor %}
    </ul> -->

    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}

    <form action="{% url 'music:favorite' album.id %}" method="POST">
        {% csrf_token %}
        {% for song in album.song_set.all %}
            <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}" />
            <label for="song{{ forloop.counter }} ">
                {{ song.song_title }}
                {% if song.is_favorite %}
                    <img src="templates/music/1200px-Gold_Star.svg" /> <!--not valid image****-->
                {% endif %}
            </label><br>
        {% endfor %}
        <input type="submit" value="Favorite">
    </form>

{% endblock %}

music/templates/music/form-template.html
{% for fiels in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small"> {{field.errors}} </span>
        </div>
        <label class="control-label col-sm-2"> {{feild.label_tag}} </label>
        <div class="col-sm-10"> {{field}} </div>
    </div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}

{% block body %}

    {% if all_albums %}
        <h3>Here are all my Albums:</h3>
        <ul>
            {% for album in all_albums %}
            <li><a href = "{% url 'music:detail' album.id %}"> {{album.album_title}} </a></li>
            {% endfor %}
        </ul>
    {% else %}
        <h3>You don't have any albums</h3>
    {% endif %}

{% endblock %}